spring:
  profiles: 
    active:
     -dev
---
server:
   port:8201
spring:
  profiles: dev
  application:
    name:winery-config-client
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:1111/eureka
---
server:
   port:8202
spring:
  profiles: test
  application:
    name:winery-config-client
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:1111/eureka
